#!/bin/bash

if grep 'multilib' /etc/pacman.conf
then
	echo "Image is x86"
	echo "Enabling Multilib"
	sed -i 's/#\[multilib\]/[multilib]/g' /etc/pacman.conf
	sed -i '/\[multilib\]/a Server = https://repo.mcld.eu/repo/archlinux/$repo/os/$arch\nInclude = /etc/pacman.d/mirrorlist' /etc/pacman.conf
else
	echo "Not x86"
fi
