#!/bin/bash

if grep 'CARCH="x86_64"' /etc/makepkg.conf
then
	echo "Image is x86"
	echo "Adding x86 mirror"
	sed -i '/\[core\]/a Server = https://repo.mcld.eu/repo/archlinux/$repo/os/$arch' /etc/pacman.conf
	sed -i '/\[extra\]/a Server = https://repo.mcld.eu/repo/archlinux/$repo/os/$arch' /etc/pacman.conf
elif grep 'CARCH="aarch64"' /etc/makepkg.conf
then
	echo "Image is ARM64"
	echo "Adding ARM64 mirror"
	sed -i '/\[core\]/a Server = https://repo.mcld.eu/repo/arm/$arch/$repo' /etc/pacman.conf
	sed -i '/\[extra\]/a Server = https://repo.mcld.eu/repo/arm/$arch/$repo' /etc/pacman.conf
	sed -i '/\[community\]/a Server = https://repo.mcld.eu/repo/arm/$arch/$repo' /etc/pacman.conf
fi
