#!/usr/bin/env bash
# Inspired by mguentner/remote-aur-builder

set -e
export AUR_USER=builder
if [ ! -d /home/$AUR_USER/built ]; then
	sudo -u $AUR_USER mkdir /home/$AUR_USER/built
fi

sudo -u $AUR_USER bash -c "pikaur -P PKGBUILD --needed --noprogressbar --noconfirm"

find /home/$AUR_USER/.cache/pikaur/pkg -iname *pkg.tar* -exec mv "{}" /home/$AUR_USER/built/ \;
