#!/usr/bin/env bash
# Inspired by mguentner/remote-aur-builder

set -e
export AUR_USER=builder
sudo -u $AUR_USER bash -c "cd /home/$AUR_USER/ && git clone https://github.com/satcom886/pkgbuilds"
if [ ! -d /home/$AUR_USER/built ]; then
	sudo -u $AUR_USER mkdir /home/$AUR_USER/built
fi

sudo -u $AUR_USER bash -c "cd /home/$AUR_USER/pkgbuilds/PKGBUILDs/$1 && pikaur -P PKGBUILD --needed --noprogressbar --noconfirm"

find /home/$AUR_USER/.cache/pikaur/pkg -iname *pkg.tar* -exec mv "{}" /home/$AUR_USER/built/ \;
